- Functions/Functions/Bookmarks/BookmarkRuleFunction.cs
- Functions/Functions/Bookmarks/RemoveBookmarkFunction.cs
- Functions/Functions/Reactions/ReactFunction.cs
- Functions/Functions/Reactions/RemoveReactionFunction.cs
- Functions/Functions/User/AddUserOrganisationFunction.cs
Do more thorough data validation
> 🚑  Fix empty data in CosmosDB

- .github/workflows/release.yml
See https://github.com/Azure/arm-deploy/issues/48#issuecomment-855672293
This is a temporary fix until the actual problem is resolved.
issue: https://github.com/SSWConsulting/SSW.Rules/issues/470
> 📌  Use temporary fix

- .gitignore
- Functions/Functions/AuthCMS/AuthenticateNetlify.cs
- Functions/Functions/AuthCMS/NetlifyCallback.cs
- Functions/local.settings.template.json
Adding my changes back. They were removed as I thought they were the cause of the problem
Reverts SSWConsulting/SSW.Rules.Functions#27
> Revert "Revert "Add Netlify CMS Authentication functions""

- Functions/Domain/RuleHistoryCache.cs
- Functions/Functions/History/GenerateHistoryFileFunction.cs
- Functions/Functions/History/UpdateRuleHistory.cs
Changed date fields to DateTime
> Added date time formats and parsing

- Azure/Azure.fsproj
- Azure/Program.fs
- SSW.Rules.AzFuncs/Functions/AuthCMS/AuthenticateCMS.cs
- SSW.Rules.AzFuncs/Functions/AuthCMS/CMSCallback.cs
adds dotnet-isolated + github token to arm
> Updates Arm config 

- SSW.Rules.AzFuncs/Domain/LatestRules.cs
- SSW.Rules.AzFuncs/Functions/Widget/UpdateLatestRules.cs
- Checks if latest Rules table already includes the rule. Updates or Creates 
- Adds the Rules Guid to be able to tell
> Fix updating latest rules

- .github/workflows/build.yml
- .github/workflows/release.yml
- SSW.Rules.AzFuncs/Functions/Widget/GetLatestRules.cs
- Adds to `build.yml` and `release.yml` a new GitHub token `AZ_FUNC_GITHUB_PAT`
- Fixes GetLatestRules Exception 
NEED TO ADD A SECRET TO THIS REPO: `AZ_FUNC_GITHUB_PAT` 
1. Generate a GitHub PAT 
1. Add it to a new secret `AZ_FUNC_GITHUB_PAT`
> Add GITHUB_TOKEN secret

- .github/workflows/build.yml
- .github/workflows/release.yml
- Azure/Program.fs
- Adds `CMS_OAUTH_CLIENT_ID` 
- Adds `CMS_OAUTH_CLIENT_SECRET`
Need to add this to GitHub: `CMS_OAUTH_CLIENT_ID` + `CMS_OAUTH_CLIENT_SECRET`
> Update Program.fs with CMS_OAUTH secrets

- SSW.Rules.AzFuncs/Functions/Bookmarks/BookmarkRuleFunction.cs
- SSW.Rules.AzFuncs/docs/Functions/Functions.http
Added all Azure Functions to Functions.http for manual testing. 
Except for the following functions, as they need data from the GitHub flow:
- UpdateHistorySyncCommitHash
- UpdateRuleHistory
- UpdateLatestRules
> ✨ Update .http File For Manual Testing

- SSW.Rules.AzFuncs/Functions/User/ConnectUserToCommentsFunction.cs
- SSW.Rules.AzFuncs/helpers/Utils.cs
Relates to https://github.com/SSWConsulting/SSW.Rules/issues/1185
As per my conversation with @JackDevAU, it's better to fix the display issue in the backend instead of changing the frontend code.
This PR:
- Changed the function name from ConnectUserToCommentsFunctiont to ConnectUserCommentsFunction
- Updated JSON settings to use camel case
> 🐛 Fix Display Issue on Profile Page

- SSW.Rules.AzFuncs/Functions/Widget/UpdateLatestRules.cs
I merged a giant PR and it caused this to break.
If you are changing 100 files we dont want this in the widget anyway - it will mean you are doing something automated and will make the data in the widget look silly
> Ensure PRs are under 101 files changed

- SSW.Rules.AzFuncs/Domain/FrontMatter.cs
- SSW.Rules.AzFuncs/Functions/Widget/UpdateLatestRules.cs
For https://github.com/SSWConsulting/SSW.Rules/issues/1367
> Add SEO Description to avoid warning

- SSW.Rules.AzFuncs/Functions/History/UpdateRuleHistory.cs
> Remove unnecessary created date update

- .github/workflows/build.yml
- .github/workflows/release.yml
Updating packages in github actions to fix failing build
> Update packages 2

- Azure/Azure.fsproj
- OidcApiAuthorization/OidcApiAuthorization.csproj
- SSW.Rules.AzFuncs/SSW.Rules.AzFuncs.csproj
This reverts commit 25d1d91d4cfb897556feadcee73618a4c03ba1a8.
> Revert "Updated packages (#66)"

- SSW.Rules.AzFuncs/SSW.Rules.AzFuncs.csproj
> 📦 Upgraded package 2 - Microsoft.Azure.Functions.Worker

- SSW.Rules.AzFuncs/SSW.Rules.AzFuncs.csproj
> 📦 Upgraded package 3 - Microsoft.Azure.Functions.Worker.ApplicationInsights

- SSW.Rules.AzFuncs/SSW.Rules.AzFuncs.csproj
> 📦 Upgraded package 4 - Microsoft.Azure.Functions.Worker.Extensions.Http

- SSW.Rules.AzFuncs/SSW.Rules.AzFuncs.csproj
> 📦 Upgraded package 5 - Microsoft.Azure.Functions.Worker.Sdk

- OidcApiAuthorization/OidcApiAuthorization.csproj
> 📦 Upgraded package 8 - Microsoft.Extensions.Configuration.Binder

- SSW.Rules.AzFuncs/SSW.Rules.AzFuncs.csproj
Reverts SSWConsulting/SSW.Rules.Functions#74 of Microsoft.Azure.Functions.Worker.Sdk upgrade
> Revert "📦 Upgraded package 5 - Microsoft.Azure.Functions.Worker.Sdk"

- SSW.Rules.AzFuncs/SSW.Rules.AzFuncs.csproj
> 📦 Upgraded package 7 - YamlDotNet

- OidcApiAuthorization/OidcApiAuthorization.csproj
> 📦 Upgraded package 9 - Microsoft.Extensions.Options

- OidcApiAuthorization/OidcApiAuthorization.csproj
> 📦 Upgraded package 10 - IdentityModel

- OidcApiAuthorization/OidcApiAuthorization.csproj
Relates: https://github.com/SSWConsulting/SSW.Rules.Functions/issues/68
> 📦 v2 - Upgraded package 8 - Microsoft.Extensions.Configuration.Binder

- SSW.Rules.AzFuncs/SSW.Rules.AzFuncs.csproj
> 📦 Upgraded package 6 - Octokit

- .github/workflows/build.yml
- .github/workflows/release.yml
- Azure/Program.fs
Added CORS origins when creating ARM template for functions
> ⚙️ Added CORS origins

- SSW.Rules.AzFuncs/Functions/Bookmarks/BookmarkRuleFunction.cs
- SSW.Rules.AzFuncs/Functions/Bookmarks/GetAllBookmarkedFunction.cs
- SSW.Rules.AzFuncs/Functions/Bookmarks/RemoveBookmarkFunction.cs
Issue: https://github.com/SSWConsulting/SSW.Rules/issues/1580
This pull request includes several changes to the `SSW.Rules.AzFuncs` project, focusing on refactoring and improving the consistency of the bookmark-related Azure Functions. The most important changes include response handling(One function was returning 500 even the operation was success), renaming variables for clarity, removing unused imports, and improving the logging.
Refactoring and Code Cleanup:
* `SSW.Rules.AzFuncs/Functions/Bookmarks/BookmarkRuleFunction.cs`
* `SSW.Rules.AzFuncs/Functions/Bookmarks/GetAllBookmarkedFunction.cs`
* `SSW.Rules.AzFuncs/Functions/Bookmarks/RemoveBookmarkFunction.cs`
> ♻️ Refactored Bookmarks Azure Functions
